/*
 * STUDENT ID:      816036508
 * STUDENT NAME:    Jonathan Mohammed
 */

import java.util.Random;

public class ChatBot
{
    // Attributes
    private String chatBotName;
    private int numResponsesGenerated;
    private static final int messageLimit;
    private static int messageNumber;
    
    
    // Static Attribute initialisation
    static {
        messageLimit = 10;
        messageNumber = 0;
    }
    
    
    // Constructor - Default no argument
    public ChatBot() {
        this.chatBotName = ChatBotGenerator.generateChatBotLLM(0);
        this.numResponsesGenerated = 0;
    }
    
    // Constructor - Overloaded one argument
    public ChatBot(int LLMCode) {
        this.chatBotName = ChatBotGenerator.generateChatBotLLM(LLMCode);
        this.numResponsesGenerated = 0;
    }
    
    
    // Accessors
    public String getChatBotName() {
        return chatBotName;
    }
    
    public int getNumResponsesGenerated() {
        return numResponsesGenerated;
    }
    
    public static int getMessageLimit() {
        return messageLimit;
    }
    
    public static int getTotalNumResponsesGenerated() {
        return messageNumber;
    }
    
    
    // Mutators
    public void setNumResponsesGenerated(int numResponsesGenerated) {
        this.numResponsesGenerated = numResponsesGenerated;
    }
    
    public static void setMessageNumber(int newMessageNumber) {
        messageNumber = newMessageNumber;
    }
    
    
    // Methods
    public static int getTotalNumMessagesRemaining() {
        int limit = getMessageLimit();
        int totalMessages = getTotalNumResponsesGenerated();
        return (limit - totalMessages);
    }
    
    public static boolean limitReached() {
        return (getTotalNumMessagesRemaining() == 0);
    }
    
    private String generateResponse() {
        // Incrementing the number of messages generated by the ChatBot
        int newNumResponses = getNumResponsesGenerated() + 1;
        setNumResponsesGenerated(newNumResponses);
        
        // Incrementing the number of messages generated by all ChatBots
        int newMessageNumber = getTotalNumResponsesGenerated() + 1;
        setMessageNumber(newMessageNumber);
        
        return ("(Message# " + newMessageNumber + ") Response from " + getChatBotName() + " \t" + ">> generatedTextHere");
    }
    
    public String prompt(String requestMessage) {
        if (!limitReached()) {
            return generateResponse();
        }
        
        return "Daily Limit Reached. Wait 24 hours to resume chatbot usage";
    }
    
    public String toString() {
        return ("ChatBot Name: " + getChatBotName() + " \t" + "Number Messaged Used: " + getNumResponsesGenerated());
    }
}